## Helper functions

In [1]:
def asciiToNum(string:str)->int:
    ans = 0
    for i in string:
        ans = ans + ord(i)
    return ans

In [14]:
def add100(num:int):
    ans = []
    for i in range(5):
        ans.append(num + i*100)
    return ans

def add50(num:int):
    ans = []
    for i in range(5):
        ans.append(num + i*50)
    return ans

def add1(num:int):
    ans = []
    for i in range(5):
        ans.append(num + i*1)
    return ans

## Inputs

In [39]:
name = asciiToNum("JYOTHIKRISHNA")
rollno = asciiToNum("EC21B1022")
marks = 11
ascii_name = add100(name)
ascii_rollno = add50(rollno)
quizmarks = add1(marks)


## Making a df

In [21]:
import pandas as pd

In [45]:
df = pd.DataFrame({"ASCII_Name": ascii_name, "ASCII_RollNumber" : ascii_rollno, "Quiz_1_Marks": quizmarks})
df

ASCII_Name  ASCII_RollNumber  Quiz_1_Marks
0         999               498            11
1        1099               548            12
2        1199               598            13
3        1299               648            14
4        1399               698            15

## Normalization

In [72]:
normalized_df = (df - df.mean()) / df.std()
normalized_df

ASCII_Name  ASCII_RollNumber  Quiz_1_Marks
0   -1.264911         -1.264911     -1.264911
1   -0.632456         -0.632456     -0.632456
2    0.000000          0.000000      0.000000
3    0.632456          0.632456      0.632456
4    1.264911          1.264911      1.264911

## Finding covariance matrix

In [73]:
covariance_matrix = normalized_df.cov()
covariance_matrix

ASCII_Name  ASCII_RollNumber  Quiz_1_Marks
ASCII_Name               1.0               1.0           1.0
ASCII_RollNumber         1.0               1.0           1.0
Quiz_1_Marks             1.0               1.0           1.0

## Finding eigenvalues and eigenvectors

In [74]:
import numpy as np

In [75]:
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
eigenvalues, eigenvectors

(array([-2.22044605e-16,  3.00000000e+00, -3.25176795e-17]),
 array([[-0.81649658,  0.57735027,  0.08048631],
        [ 0.40824829,  0.57735027, -0.74390605],
        [ 0.40824829,  0.57735027,  0.66341974]]))

## Choosing columns 2 and 3

In [76]:
eigenvectors2 = eigenvectors[:,1:]
eigenvectors2

array([[ 0.57735027,  0.08048631],
       [ 0.57735027, -0.74390605],
       [ 0.57735027,  0.66341974]])

## Finding new data

In [88]:
new_df = np.matmul(normalized_df,eigenvectors2)
new_df

0             1
0 -2.190890  1.051222e-16
1 -1.095445  5.256112e-17
2  0.000000  0.000000e+00
3  1.095445 -5.256112e-17
4  2.190890 -1.051222e-16

## Adding labels back

In [90]:
new_df.rename(columns={"0": "ASCII_RollNumber", "1": "Quiz_1_Marks"})
new_df

0             1
0 -2.190890  1.051222e-16
1 -1.095445  5.256112e-17
2  0.000000  0.000000e+00
3  1.095445 -5.256112e-17
4  2.190890 -1.051222e-16